// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hiypurwywcvlrwlmopdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpeXB1cnd5d2N2bHJ3bG1vcGRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5OTU3NjMsImV4cCI6MjA2OTU3MTc2M30.ebWiw6NF0074LNM6uCxeqMoM-k4a4sHdRRnkNLG5McE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});